blank_issues_enabled: false
contact_links:
  - name: Vorschläge zu anderen Themen
    url: mailto:josua.hess@baumpflege-treske.de
    about: Wenn du Vorschläge zu Themen hast, die nicht die Website betrifft, klickt bitte hier.
